baseURL: 'https://toretto460.github.io/'
languageCode: 'en-us'
title: "Simone's blog"
theme: "papermod"
params:
  defaultTheme: light
  github: toretto460
markup:
  goldmark:
    renderer:
      unsafe: true